In [4]:
import numpy as np

# Seeds

### numpy.random.RandomState

The data generation functions in numpy.random use a global random seed. To avoid
global state, you can use numpy.random.RandomState to create a random number
generator isolated from others

numpy.random.RandomState is a container for the Mersenne Twister pseudo-random number generator.

A pseudorandom number generator (PRNG), also known as a deterministic random bit generator (DRBG),[1] is an algorithm for generating a sequence of numbers whose properties approximate the properties of sequences of random numbers. 

In [5]:
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

### numpy.random.seed

This method is called when RandomState is initialized. 

If you set the np.random.seed(a_fixed_number) every time you call the numpy's other random function, the result will be the same:

In [6]:
# np.random.seed(0) makes the random numbers predictable

np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [7]:
# np.random.seed(0) makes the random numbers predictable

np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [12]:
numbers = [10, 20, 30, 40, 50, 60]
print ("Original list: ", numbers )

np.random.seed(4)
np.random.shuffle(numbers)
print("Reshuffled list ", numbers)

numbers = [10, 20, 30, 40, 50, 60]
np.random.seed(4)
np.random.shuffle(numbers)
print("reshuffled list ", numbers)

Original list:  [10, 20, 30, 40, 50, 60]
Reshuffled list  [50, 60, 40, 10, 20, 30]
reshuffled list  [50, 60, 40, 10, 20, 30]


Reference:

https://en.wikipedia.org/wiki/Mersenne_Twister
    
https://en.wikipedia.org/wiki/Pseudorandom_number_generator

https://pynative.com/python-random-seed/